// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxsxmvxtblcideimcgnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94c3htdnh0YmxjaWRlaW1jZ25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NDk1NjEsImV4cCI6MjA5MTMyNTU2MX0.M4zHbymLrUQfaGFbLE7CZv-saz1KkvJIIFMMKw7afW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});